### ISSUE TITLE
YouTube - Direct play PlexIt not working

### ISSUE THREAD

**Issue by dough321** [plexinc-plugins/Services.bundle#955]
Youtube videos show up in the queue fine. But can't play them.

**Comment by sander1** [comment]
Is this with PMS 1.4.x and/org Plex/Web 3.x by any chance?

**Comment by dough321** [comment]
I am not running PMS. I am using Plex/Web on Roku Plex Channel v4.3.0 and Plex Classic v3.1.9 ( direct play). Both have this issue.

**Comment by sander1** [comment]
> I am not running PMS

:-? You can't use the Watch Later option if you're not using Plex Media Server somehow.

**Comment by dough321** [comment]
I have been using Plex direct play for 3 plus years and youtube was working fine. Is it possible latest commit broke it ? Or google might have changed something at their end. How come dailymotion is working fine ?

**Comment by sander1** [comment]
It doesn't look to be an issue with YouTube or Google, but with certain Plex clients. I have no problem playing YT videos on my Android TV, but the web client fails for every single one. I've opened an issue with the web client, because it does not seem to be an issue with the YT URL Service.

**Comment by shopgirl284** [comment]
A Plex Media Server is required for Watch Later media if that media is not compatible with and will not direct play on the player/device you are using. Any Watch Later media that cannot direct play on your player/device must be transcoded and transcoding requires a Plex Media Server. https://forums.plex.tv/discussion/comment/1476038/#Comment_1476038

The Roku Media Player can not direct play some newer YouTube videos due to changes YouTube made to the codec/format of its videos. This is an issue with the Roku player software (not the Plex app for Roku) and was reported to Roku in April, but Roku has yet to fix its direct play issue with newer YouTube videos. https://forums.plex.tv/discussion/comment/1164476/#Comment_1164476

Also, there is currently an issue with the Plex Web app on the Chrome browser playing YouTube videos due to a POST request error. This issue has been reported to the Plex Web app devleopers - https://forums.plex.tv/discussion/272005/unable-to-play-watch-later-youtube-videos-on-plex-web

**Comment by tscibilia** [comment]
I have the same issue; however, I noticed that the console logs an error. The browser is trying to load mixed media content (http instead of https) and it's not playing for me. 


> Mixed Content: The page at '...myplexwebpage...' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://node.plexapp.com:32400/system/services/url/lookup?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DIsi-lU_sDBQ&includeConcerts=1&includeExtras=1&includeOnDeck=1&includePopularLeaves=1&includeChapters=1&checkFiles=1&X-Plex-Product=Plex%20Web&X-Plex-Version=3.20.4&X-Plex-Client-Identifier=0fe7xrz8ifmf8e46qrnfeiuf&X-Plex-Platform=Chrome&X-Plex-Platform-Version=61.0&X-Plex-Device=Windows&X-Plex-Device-Name=Plex%20Web%20%28Chrome%29&X-Plex-Device-Screen-Resolution=1272x301%2C1680x1050&X-Plex-Token=xmqrFuHz7qjyswNJyVvM'. This request has been blocked; the content must be served over HTTPS.

**Comment by sander1** [comment]
This is not an issue with the `Services.bundle`.

Problems reported 10 Apr 2017 in `plex-web-client-issues`, not a web client issue, so passed on to PMS team on 4 May 2017 (https://github.com/plexinc/plex-web-client-issues/issues/218)

Problems reported again 18 Aug 2017 in `plex-web-client-issues`, probable fix added on 22 Aug 2017. Not a web client issue (which we now know for sure), so passed on to PMS team 22 Aug 2017 (https://github.com/plexinc/plex-web-client-issues/issues/224)
